// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXdZXs1qCfBv0kDwG44jf5MYnmHnfpyVM',
    appId: '1:343108349304:web:c07dde1e1ff1ae6128ac8d',
    messagingSenderId: '343108349304',
    projectId: 'movil-agenda-sw1-p2',
    authDomain: 'movil-agenda-sw1-p2.firebaseapp.com',
    storageBucket: 'movil-agenda-sw1-p2.firebasestorage.app',
    measurementId: 'G-T0BMLECZK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTVjwWJPI5Q1wukOpADBFZ0NVNZLL2A90',
    appId: '1:343108349304:android:43ce0fbf1722851828ac8d',
    messagingSenderId: '343108349304',
    projectId: 'movil-agenda-sw1-p2',
    storageBucket: 'movil-agenda-sw1-p2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRY5Yr24DxoJKr4ccUgcIR8hEZMUK8AHw',
    appId: '1:343108349304:ios:c62738f1ce1aa9a628ac8d',
    messagingSenderId: '343108349304',
    projectId: 'movil-agenda-sw1-p2',
    storageBucket: 'movil-agenda-sw1-p2.firebasestorage.app',
    iosBundleId: 'com.example.movilAgendaSw1P2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRY5Yr24DxoJKr4ccUgcIR8hEZMUK8AHw',
    appId: '1:343108349304:ios:c62738f1ce1aa9a628ac8d',
    messagingSenderId: '343108349304',
    projectId: 'movil-agenda-sw1-p2',
    storageBucket: 'movil-agenda-sw1-p2.firebasestorage.app',
    iosBundleId: 'com.example.movilAgendaSw1P2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXdZXs1qCfBv0kDwG44jf5MYnmHnfpyVM',
    appId: '1:343108349304:web:51a28686db0577f228ac8d',
    messagingSenderId: '343108349304',
    projectId: 'movil-agenda-sw1-p2',
    authDomain: 'movil-agenda-sw1-p2.firebaseapp.com',
    storageBucket: 'movil-agenda-sw1-p2.firebasestorage.app',
    measurementId: 'G-VHH3FFXHPV',
  );

}